const languages = [
  {
    'name': 'Afrikaans',
    'transcribe': 'af-ZA',
    'translate': 'af',
    'code': 'ZA',
  },
  {
    'name': 'Basque',
    'transcribe': 'eu-ES',
    'translate': 'eu',
    'code': 'EU',
  },
  {
    'name': 'Bulgarian',
    'transcribe': 'bg-BG',
    'translate': 'bg',
    'code': 'BG',
  },
  {
    'name': 'Catalan',
    'transcribe': 'ca-ES',
    'translate': 'ca',
    'code': 'ES',
  },
  {
    'name': 'Chinese (Simplified Mandarin, China)',
    'transcribe': 'cmn-Hans-CN',
    'translate': 'zh-CN',
    'code': 'CN',
    'shortName': 'Chinese',
  },
  {
    'name': 'Chinese (Simplified Mandarin, Hong Kong)',
    'transcribe': 'cmn-Hans-HK',
    'translate': 'zh-CN',
    'code': 'HK',
    'shortName': 'Chinese',
  },
  {
    'name': 'Chinese (Traditional Cantonese, Hong Kong)',
    'transcribe': 'yue-Hant-HK',
    'translate': 'zh-TW',
    'code': 'HK',
    'shortName': 'Cantonese',
  },
  {
    'name': 'Chinese (Traditional Mandarin, Taiwan)',
    'transcribe': 'cmn-Hans-TW',
    'translate': 'zh-TW',
    'code': 'TW',
    'shortName': 'Chinese',
  },
  {
    'name': 'Croatian',
    'transcribe': 'hr-HR',
    'translate': 'hr',
    'code': 'HR',
  },
  {
    'name': 'Czech',
    'transcribe': 'cs-CZ',
    'translate': 'cs',
    'code': 'CZ',
  },
  {
    'name': 'Dutch',
    'transcribe': 'nl-NL',
    'translate': 'nl',
    'code': 'NL',
  },
  {
    'name': 'English (Australia)',
    'transcribe': 'en-AU',
    'translate': 'en',
    'code': 'AU',
    'shortName': 'English',
  },
  {
    'name': 'English (Canada)',
    'transcribe': 'en-CA',
    'translate': 'en',
    'code': 'CA',
    'shortName': 'English',
  },
  {
    'name': 'English (India)',
    'transcribe': 'en-IN',
    'translate': 'en',
    'code': 'IN',
    'shortName': 'English',
  },
  {
    'name': 'English (New Zealand)',
    'transcribe': 'en-NZ',
    'translate': 'en',
    'code': 'NZ',
    'shortName': 'English',
  },
  {
    'name': 'English (South Africa)',
    'transcribe': 'en-ZA',
    'translate': 'en',
    'code': 'ZA',
    'shortName': 'English',
  },
  {
    'name': 'English (United Kingdom)',
    'transcribe': 'en-GB',
    'translate': 'en',
    'code': 'GB',
    'shortName': 'English',
  },
  {
    'name': 'English (United States)',
    'transcribe': 'en-US',
    'translate': 'en',
    'code': 'US',
    'shortName': 'English',
  },
  {
    'name': 'Spanish (Argentina)',
    'transcribe': 'es-AR',
    'translate': 'es',
    'code': 'AR',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Bolivia)',
    'transcribe': 'es-BO',
    'translate': 'es',
    'code': 'BO',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Chile)',
    'transcribe': 'es-CL',
    'translate': 'es',
    'code': 'CL',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Colombia)',
    'transcribe': 'es-CO',
    'translate': 'es',
    'code': 'CO',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Costa Rica)',
    'transcribe': 'es-CR',
    'translate': 'es',
    'code': 'CR',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Dominican Republic)',
    'transcribe': 'es-DO',
    'translate': 'es',
    'code': 'DO',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Ecuador)',
    'transcribe': 'es-EC',
    'translate': 'es',
    'code': 'EC',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (El Salvador)',
    'transcribe': 'es-SV',
    'translate': 'es',
    'code': 'SV',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Guatemala)',
    'transcribe': 'es-GT',
    'translate': 'es',
    'code': 'GT',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Honduras)',
    'transcribe': 'es-HN',
    'translate': 'es',
    'code': 'HN',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Mexico)',
    'transcribe': 'es-MX',
    'translate': 'es',
    'code': 'MX',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Nicaragua)',
    'transcribe': 'es-NI',
    'translate': 'es',
    'code': 'NI',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Panama)',
    'transcribe': 'es-PA',
    'translate': 'es',
    'code': 'PA',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Paraguay)',
    'transcribe': 'es-PY',
    'translate': 'es',
    'code': 'PY',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Peru)',
    'transcribe': 'es-PE',
    'translate': 'es',
    'code': 'PE',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Puerto Rico)',
    'transcribe': 'es-PR',
    'translate': 'es',
    'code': 'PR',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Spain)',
    'transcribe': 'es-es',
    'translate': 'es',
    'code': 'ES',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (United States)',
    'transcribe': 'es-US',
    'translate': 'es',
    'code': 'US',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Uruguay)',
    'transcribe': 'es-UY',
    'translate': 'es',
    'code': 'UY',
    'shortName': 'Spanish',
  },
  {
    'name': 'Spanish (Venezuela)',
    'transcribe': 'es-VE',
    'translate': 'es',
    'code': 'VE',
    'shortName': 'Spanish',
  },
  {
    'name': 'Finnish',
    'transcribe': 'fi-FI',
    'translate': 'fi',
    'code': 'FI',
  },
  {
    'name': 'French',
    'transcribe': 'fr-FR',
    'translate': 'fr',
    'code': 'FR',
  },
  {
    'name': 'Galician',
    'transcribe': 'gl-ES',
    'translate': 'gl',
    'code': 'ES',
  },
  {
    'name': 'German',
    'transcribe': 'de-DE',
    'translate': 'de',
    'code': 'DE',
  },
  {
    'name': 'Hungarian',
    'transcribe': 'hu-HU',
    'translate': 'hu',
    'code': 'HU',
  },
  {
    'name': 'Icelandic',
    'transcribe': 'is-IS',
    'translate': 'is',
    'code': 'IS',
  },
  {
    'name': 'Indonesian',
    'transcribe': 'id-ID',
    'translate': 'id',
    'code': 'ID',
  },
  {
    'name': 'Italian (Italy)',
    'transcribe': 'it-IT',
    'translate': 'it',
    'code': 'IT',
    'shortName': 'Italian',
  },
  {
    'name': 'Italian (Switzerland)',
    'transcribe': 'it-CH',
    'translate': 'it',
    'code': 'CH',
    'shortName': 'Italian',
  },
  {
    'name': 'Japanese',
    'transcribe': 'ja-JP',
    'translate': 'ja',
    'code': 'JP',
  },
  {
    'name': 'Korean',
    'transcribe': 'ko-KR',
    'translate': 'ko',
    'code': 'KR',
  },
  {
    'name': 'Latin',
    'transcribe': 'la',
    'translate': 'la',
    'code': 'LA',
  },
  {
    'name': 'Malay',
    'transcribe': 'ms-MY',
    'translate': 'ms',
    'code': 'MY',
  },
  {
    'name': 'Norwegian',
    'transcribe': 'no-NO',
    'translate': 'no',
    'code': 'NO',
  },
  {
    'name': 'Polish',
    'transcribe': 'pl-PL',
    'translate': 'pl',
    'code': 'PL',
  },
  {
    'name': 'Portuguese (Brasil)',
    'transcribe': 'pt-BR',
    'translate': 'pt',
    'code': 'BR',
    'shortName': 'Portuguese',
  },
  {
    'name': 'Portuguese (Portugal)',
    'transcribe': 'pt-PT',
    'translate': 'pt',
    'code': 'PT',
    'shortName': 'Portuguese',
  },
  {
    'name': 'Romanian',
    'transcribe': 'ro-RO',
    'translate': 'ro',
    'code': 'RO',
  },
  {
    'name': 'Russian',
    'transcribe': 'ru-RU',
    'translate': 'ru',
    'code': 'RU',
  },
  {
    'name': 'Serbian',
    'transcribe': 'sr-RS',
    'translate': 'sr',
    'code': 'RS',
  },
  {
    'name': 'Slovak',
    'transcribe': 'sk-SK',
    'translate': 'sk',
    'code': 'SK',
  },
  {
    'name': 'Swedish',
    'transcribe': 'sv-SE',
    'translate': 'sv',
    'code': 'SE',
  },
  {
    'name': 'Turkish',
    'transcribe': 'tr-TR',
    'translate': 'tr',
    'code': 'TR',
  },
  {
    'name': 'Zulu',
    'transcribe': 'zu-ZA',
    'translate': 'zu',
    'code': 'ZA',
  },
];

export { languages };
